set nocompatible

set number

syntax on

" For vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()

" PLUGINS
Bundle 'scrooloose/nerdtree'

" NERD Tree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif
